language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: OV3jW0FeAufZVgAQtzyAoKYauc4RRXu/3i63TUN4q7JtsD0SS+ErzT9CXUchbZx72t3fcShaVAbNoRWm/M8h2GLtKu93a0Gto4PJFRNKzjwYX6sWDbUy+nlb7yQNvK/rDAvvDSijDsKU5wTd4OkHaarYTjs/UK2VEa8fb/R7g8NP84q46zKxr81xkGZC1mF0U1BXbxdicLMYkXaZKkCGLUBHo6T2FDW11lmW4yu9iuobfIA6Y/x78PeCTFnEIBCaTAwC6RarC4rKWQrcj2KMq4dpZWU6l7IzeBg27ly12DjA0GTv8sawNKToNs8zfivyMwnpK3XJWBwMPbZ0jphdX7xYLZ+WuhqEF+yHFnjLGUFcKE8PU0UdafXWiKAqTOWzpco8E6UVBCVpCG4bS13EVwahhNlPiDzlNLppeuEbYtm/Y3TFSSlHwlDKfXsuqVBv0/DlN/sahS2sLLXwcFUbwD9JKxTy4Q2MvXOIxMlzvB+rGgvSfCHWbpSrIVycDG0t/rK/OdYWJjNQyv3RymWk8HryZ1zGaA0imLThIeIf+H9CjGygIxOemd/mrSvPouBqBR0/bu0XDCY7ASnvcqbuHJT1wzUl7CPe8VWkoCMfdhZwH9tNIbGojhrChdamO16vzost9oi23EMD0LnSZ4bbqYu40YXMDsxencZ33NlUuhs=
  app: 
  run: rails db:migrate
