language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: UtMbxdhkGTgDJUfSPj1YTYzOT3c6TIuBy2Syd717PKmtx/3s0rIaBy7ddDu0uKnkubdPgFLFcd+/IJW2Qdls82uNSz2ar0D82d/OL0zR84way4Jtj4/haBKWL/Wp/P1ijuRomLThDhRXHe58KlIPPyuzjp9ds7NlWzw14HpAoCVqkubPV1KXfmrE4zWGvSNCfuiwRM/6h/OeoCKMnODWsFybrro9bCP9coq2mpUB3zhVySVXPR5ehnU+CiN3BU2xI7voFghLaE0EhD5mM3a1JaTnbkmbBmK11qDUYnqmjsYxYpL6RCQr52vq3ltIkgQzSmsA5iJ2H4eT+aX+fqZixG1D2cMQpD3BrcP5fdeLZ5LTXulNWefYK5vNszbB4ITPbKtBNQ6xl5izH/wbxsVmN7naTkoTYNzIzLX0xvC8/DZQ0hrkwM824owkRNfgSTIaK8LTAxE0pGFFih7iBnScpgFCT4UqDEDc6mfgdJb8/Jbx/hu6ThqyNJSXKeCGmPzLqr22JO/Vp1sYEoq0D1qrk88jF5nrHimzDy350qsE8sgqmLzijQmhk4/I8A5ozpcHWg3ZBsc3RImgINVotauCX3HT+bue0TRm7b1ywa4KjzHUCBf7SDUtWIXbev19LPcMNRJrwcoCnte9nu7MpCHV9GPJxoi1xSjqrYMYjY+cAAg=
  app: viewing_party
  run: rails db:migrate
