language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: UtMbxdhkGTgDJUfSPj1YTYzOT3c6TIuBy2Syd717PKmtx/3s0rIaBy7ddDu0uKnkubdPgFLFcd+/IJW2Qdls82uNSz2ar0D82d/OL0zR84way4Jtj4/haBKWL/Wp/P1ijuRomLThDhRXHe58KlIPPyuzjp9ds7NlWzw14HpAoCVqkubPV1KXfmrE4zWGvSNCfuiwRM/6h/OeoCKMnODWsFybrro9bCP9coq2mpUB3zhVySVXPR5ehnU+CiN3BU2xI7voFghLaE0EhD5mM3a1JaTnbkmbBmK11qDUYnqmjsYxYpL6RCQr52vq3ltIkgQzSmsA5iJ2H4eT+aX+fqZixG1D2cMQpD3BrcP5fdeLZ5LTXulNWefYK5vNszbB4ITPbKtBNQ6xl5izH/wbxsVmN7naTkoTYNzIzLX0xvC8/DZQ0hrkwM824owkRNfgSTIaK8LTAxE0pGFFih7iBnScpgFCT4UqDEDc6mfgdJb8/Jbx/hu6ThqyNJSXKeCGmPzLqr22JO/Vp1sYEoq0D1qrk88jF5nrHimzDy350qsE8sgqmLzijQmhk4/I8A5ozpcHWg3ZBsc3RImgINVotauCX3HT+bue0TRm7b1ywa4KjzHUCBf7SDUtWIXbev19LPcMNRJrwcoCnte9nu7MpCHV9GPJxoi1xSjqrYMYjY+cAAg=
  app: viewing_party
  run: rails db:migrate
env:
  global:
    secure: dMXmmXOeVeq+vKNDJNEzaDLyNEke2oRs6Gi0cVZKKdMEGfax5Lh45bNoGjQaYYiG1Kg3Ml0M06R1Kuhx0DgyGUynrR/hrhslsIg3F569L2sb4VtTkLBHDaDsu+kTpjoEPTUp8DKLlgjH/wnT5Q6kWITYRCCDXa1gbc1Bzpfw24Kwg9Y2WFNMVsaTiYqCw7tKAdm2y00fpzOWriYswGN/pV4MK7gSTpv9cpnv7wuk+NqB+rFDfvPxc1vnK6IHNRPwGoh7+ShcBUazzztMl+Kr4NE00Rkje3vLK4fcPmqPdTPxQ8l3klUcioEDsk8zyGH+XtXnga9+gH4lPGyw413w5sDUgJCvlPqInzt+vcsUYr/3HGSn/DyDxb8gZKTDQbnD2mMCjIS/bbbHBYegUlavgb2Ctd1mSwqJxenQJyWg9DGsVt7ASLkh4Xf91SICnSzGS/bchUTonPxALbVfbPzdJCyC5oGQuZWI+NB1JaGRAs6YEki7uII1iZnFyiPm/UqqMTgLTL75p7lDBLY/1FJVGayehxYmpkd4IzafcDdtHdNI8YVxkz4qnjG6n/nMsgPeCMOsWe30C7eRzCT/XGLumZaLiEANnnOhHkrf/ugL4BO9rlAHYwR5bCcU8cWTTNSAsFdvBctOmVCYd6Parkepz3V2gsmJX9A1yvHSflHQVoQ=
