language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: UtMbxdhkGTgDJUfSPj1YTYzOT3c6TIuBy2Syd717PKmtx/3s0rIaBy7ddDu0uKnkubdPgFLFcd+/IJW2Qdls82uNSz2ar0D82d/OL0zR84way4Jtj4/haBKWL/Wp/P1ijuRomLThDhRXHe58KlIPPyuzjp9ds7NlWzw14HpAoCVqkubPV1KXfmrE4zWGvSNCfuiwRM/6h/OeoCKMnODWsFybrro9bCP9coq2mpUB3zhVySVXPR5ehnU+CiN3BU2xI7voFghLaE0EhD5mM3a1JaTnbkmbBmK11qDUYnqmjsYxYpL6RCQr52vq3ltIkgQzSmsA5iJ2H4eT+aX+fqZixG1D2cMQpD3BrcP5fdeLZ5LTXulNWefYK5vNszbB4ITPbKtBNQ6xl5izH/wbxsVmN7naTkoTYNzIzLX0xvC8/DZQ0hrkwM824owkRNfgSTIaK8LTAxE0pGFFih7iBnScpgFCT4UqDEDc6mfgdJb8/Jbx/hu6ThqyNJSXKeCGmPzLqr22JO/Vp1sYEoq0D1qrk88jF5nrHimzDy350qsE8sgqmLzijQmhk4/I8A5ozpcHWg3ZBsc3RImgINVotauCX3HT+bue0TRm7b1ywa4KjzHUCBf7SDUtWIXbev19LPcMNRJrwcoCnte9nu7MpCHV9GPJxoi1xSjqrYMYjY+cAAg=
  app: viewing_party
  run: rails db:migrate
env:
  global:
    secure: XJIkIkXWMqmijfmpVVFeJEoHieY7E/JLjPC4hmAfejrHJRi39WMqKNBfN1lWEJ85OLc01rle0oQR9gXQqoY7iBrn8/gEzMjG5bILPETxiCgay6Gf5RRZWSz/uSMlv940seyQbwlwTXvc8Re4nwZUAj++n7p4iYb0XQF39neYtJPa4RVnDVOdVhf0bfWA+WoWkeB+nTMb8aKLZGsFhZE/YY6GhNi/8qTDdUuoPLU0UxGE6/YmfZTr//KhIEBvt8/0utjbtb997BwUKIhQXRsNmW3qO60XanBEzKwJiHeEcdTsx0Fj9k8152qgu1eGJFoDpEjOHbc09GXkhdjP4t0j0P8m4iELASo+CYh7yxZ8Hl/rVTVnFVGX2zpvSxezhD9X3H5u/wNHOH80kNPQrti2dNpbRK5AjfPlpmO67Wqfj9/5Be+qt3ZJkgcvdu7SuZPDD3ocDCbOcnrvcXhnxx9gjdG3gNGMj9WsZQ2h9ETzicwbPht1a1aFX2Bdl3Yhev6v+s9LOg07/vIb7S0s3FFq+jSDf5O3MeoNGnqPYXr6QtDx44q73hE2DF7Kzmo4o6tuEcjEC70fhS764dsxFHaMMbFAG6kVNQQIrAt675Z6sCEW/wma9LZdsMZad65DsojaXx3orIQvS/7w9PEed/pjja9N4NYXn0/HQSDiB53H/eQ=
